
name: Bump version (release)

on:
  push:
    branches: [ "master" ]

jobs:
  bump-version:
    name: 'Bump Version on develop'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

      #- name: "Build Changelog"
      #  id: build_changelog
      #  uses: mikepenz/release-changelog-builder-action@v3
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Create Release
      #  uses: mikepenz/action-gh-release@v0.2.0-a03
      #  with:
      #    body: ${{steps.github_release.outputs.changelog}}